### PR TITLE
Flathub versioning correction and clean-up based on app listing guidelines

### PR DESCRIPTION
**Pull request by pd-l2ork**

### CODE REVIEW

**Comment by hfiguiere** [comment]
the flatpak-builder broke this. no need to try again, it won't magically solve itself

**Comment by hfiguiere** [comment]
shared-module for lua5.3 needs fixing then updated here.

**Comment by pd-l2ork** [comment]
What can I do in the meantime? Move to lua5.4? Or is that one broken, as well?

**Comment by bbhtt** [comment]
Fixed it, try updating the shared modules https://github.com/flathub/shared-modules?tab=readme-ov-file#updating then `git add shared-modules` commit and push it.

**Comment by pd-l2ork** [comment]
> Fixed it, try updating the shared modules https://github.com/flathub/shared-modules?tab=readme-ov-file#updating then `git add shared-modules` commit and push it.

Thank you!

**Pull request merged**
