### PR TITLE
Cosmetic build script change

### PR DESCRIPTION
**Pull request by pd-l2ork**
This commit is aimed to force new build to see if we can verify the project without modifying the auto-generated github page.

### CODE REVIEW

**Comment by hfiguiere** [comment]
to verify with github you only need to login onto flathub with a github account that has both write access to this repo and admin access to the upstream repository.

https://docs.flathub.org/docs/for-app-authors/verification

**Comment by hfiguiere** [comment]
I don't see how rebuilding would change anything.

**Comment by pd-l2ork** [comment]
I thought that doing a pull request from the flathub account would not trigger this. I did not have this issue before, so I am not sure why the project has suddenly become unverified. Concurrently, I have no easy way to add the verification file to the autogenerated github.io page. I am open to any suggestions you may have.

**Comment by pd-l2ork** [comment]
> to verify with github you only need to login onto flathub with a github account that has both write access to this repo and admin access to the upstream repository.
> 
> https://docs.flathub.org/docs/for-app-authors/verification

I logged in with the same account that also hosts the original repo (pd-l2ork). So, why then did this become suddenly unverified? The only difference (I think) may have been that the pull request prior to this one was made from the project github, rather than from the flathub account.

**Comment by hfiguiere** [comment]
what do you mean by "unverified"? The badge is new but applied to package that were NOT verified prior.

**Comment by hfiguiere** [comment]
commits have nothing to do. verification is done only once. it shouldn't change.

**Comment by barthalion** [comment]
Just to clarify, you have previously verified your app by logging it to https://flathub.org and following the steps there, and this disappeared?

**Comment by pd-l2ork** [comment]
> commits have nothing to do. verification is done only once. it shouldn't change.

I did not recall having "unverified" under the project title on the project page before (see https://flathub.org/apps/io.github.pd_l2ork.Pd_L2Ork), so I assumed it had to do something with the way I did my pull request.

**Comment by pd-l2ork** [comment]
> Just to clarify, you have previously verified your app by logging it to https://flathub.org and following the steps there, and this disappeared?

I did log into the flathub.org with this same account that has write permissions to both this repo and the upstream one (https://github.com/pd-l2ork/io.github.pd_l2ork.Pd_L2Ork and https://github.com/pd-l2ork/pd-l2ork). I am, however, unable to upload the verification file since the page that is associated is autogenerated by github (as per your original instruction).

**Comment by hfiguiere** [comment]
> I did not recall having "unverified" under the project title on the project

As I said: https://github.com/flathub/io.github.pd_l2ork.Pd_L2Ork/pull/14#issuecomment-2027601319

The badge is new, but is only applied to package that never were verified.

**Comment by pd-l2ork** [comment]
> > I did not recall having "unverified" under the project title on the project
> 
> As I said: [#14 (comment)](https://github.com/flathub/io.github.pd_l2ork.Pd_L2Ork/pull/14#issuecomment-2027601319)
> 
> The badge is new, but is only applied to package that never were verified.

I see. So, how do I upload a verification file onto an auto-generated github.io page? Do I need to do the whole jekyll thing just to be able to do this?

**Comment by barthalion** [comment]
You don't need to change your website. Once you log in with your GitHub account at https://flathub.org, you can go to https://flathub.org/apps/manage/io.github.pd_l2ork.Pd_L2Ork and verify it via GitHub.

**Comment by pd-l2ork** [comment]
> You don't need to change your website. Once you log in with your GitHub account at https://flathub.org, you can go to https://flathub.org/apps/manage/io.github.pd_l2ork.Pd_L2Ork and verify it via GitHub.

I see. That was kind of confusing. I got stuck on the first option, which suggested uploading a token. Only now I realized there was a second one. Please pardon the noise. I can see now it is verified in that menu. How long before the project page reflects this update?

**Comment by barthalion** [comment]
It shouldn’t take longer than an hour — there are some moving parts and then the website cache has to expire.

**Pull request merged**
