### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by pd-l2ork**

### CODE REVIEW

**Comment by pd-l2ork** [comment]
@hfiguiere this merge has taken place 2 days ago. However, flathub page is yet to be updated. Is there a backlog or is something else afoot? Thank you.

**Comment by hfiguiere** [comment]
```
$ flatpak remote-info flathub io.github.pd_l2ork.Pd_L2Ork 
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 1

Pd-L2Ork - An open source visual programming language for multimedia, based on
Pure Data

        ID: io.github.pd_l2ork.Pd_L2Ork
       Ref: app/io.github.pd_l2ork.Pd_L2Ork/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 20240329
   License: GPL-3.0-or-later AND BSD-3-Clause
Collection: org.flathub.Stable
  Download: 211.0 MB
 Installed: 523.7 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: 138a16d1fd2a0b662310aee53b61dd9df313431bf548d26db923beff0fee2f66
    Parent: e820da138adde96533588ec6f462c0fb1757a4c9dc53c2c246abbb3b83a91dc7
   Subject: *New stable release (c1dfbb76)
      Date: 2024-10-01 18:38:47 +0000

```

it's there.

**Comment by pd-l2ork** [comment]
Thank you @hfiguiere . How did this happen and will this be a problem again next time I do a new release? If so, how do we fix this? Thanks again.

BTW, I am talking about the flathub website: https://flathub.org/apps/io.github.pd_l2ork.Pd_L2Ork

2 days ago I committed 20240930 release, per this merge.

**Comment by hfiguiere** [comment]
image

Sounds right to me.

**Comment by pd-l2ork** [comment]
I see. Must've forgotten to update the versioning in one of the flatpak files... Thanks.

**Pull request merged**
